// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions ;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'env/env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: "${Env.api_key}",
    appId: "${Env.app_id}",
    messagingSenderId: "${Env.messaging_sender_id}",
    projectId: "${Env.project_id}",
    androidClientId: "273830249825-fe9pl6akb7o1vsntb1gsc7t6vf98vsur.apps.googleusercontent.com",
    storageBucket: "rankit-74583.appspot.com",
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: "${Env.api_key}",
    appId: "${Env.app_id}",
    messagingSenderId: "${Env.messaging_sender_id}",
    projectId: "${Env.project_id}",
    storageBucket: "rankit-74583.appspot.com",
    iosClientId: '739267820418-ego0tsnaktg58eca2o74m3gqiv5sbt8c.apps.googleusercontent.com',
    iosBundleId: 'com.mapnrank.app',
  );
}
